cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: hyunsoo-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

# cors 설정
cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: ${JWT_SECRET_KEY}

dummy-data-json-path: "/Users/hanhyunsoo/Desktop/onsuyum_storage/dummy data.json"
dummy-data-images-path: "/Users/hanhyunsoo/Desktop/onsuyum_storage/download/"
alt-image-path: "/Users/hanhyunsoo/dev/project/onsuyum/src/test/java/com/onsuyum/alt.png"

spring:
  jpa:
    properties:
      hibernate.order_by.default_null_ordering: last

---
# 개발 환경
spring:
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onsuyum
    username: user
    password: user
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: jdbc:mysql://localhost:3306/onsuyum
      username: user
      password: user
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
  # Request file 설정
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
      location: /Users/hanhyunsoo/Desktop/onsuyum_storage/upload
  config:
    activate:
      on-profile: development

cors:
  allowed-origins: "http://localhost:3000"

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error;
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
# 배포 환경
# 개발 환경
spring:
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_JDBC_URL}
    username: sa
    password:
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 50
      jdbc-url: ${RDS_JDBC_URL}
      username: ${RDS_USERNAME}
      password: ${RDS_PASSWORD}
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: off
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
  # Request file 설정
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
      location: ${UPLOAD_LOCATION}
  config:
    activate:
      on-profile: production
  devtools:
    livereload:
      enabled: off

cors:
  # TODO 실제로 배포할때 localhost 제거해야함
  allowed-origins: http://localhost:3000, https://www.onsuyum.com, https://api.onsuyum.com