cloud:
  aws:
    credentials:
      accessKey: ${aws_access_key_id}
      secretKey: ${aws_secret_access_key}
    s3:
      bucket: onsuyum.bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

# cors 설정
cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: ${jwt-secret-key}

---
# 개발 환경
spring:
  # 데이터 소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/Desktop/h2/onsuyum_test;NON_KEYWORDS=USER;MODE=MySQL
    username: sa
    password:
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: jdbc:h2:tcp://localhost:9092/~/Desktop/h2/onsuyum_test;NON_KEYWORDS=USER;MODE=MySQL
      username: sa
      password:
      driver-class-name: ${spring.datasource.driver-class-name}
      data-source-properties:
        rewriteBatchedStatements: true
  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
  # Request file 설정
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
      location: /Users/hanhyunsoo/Desktop/storage
  config:
    activate:
      on-profile: development

cors:
  allowed-origins: 'http://localhost:3000'

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error;
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
# 배포 환경
spring:
  config:
    activate:
      on-profile: production